package com.notepad.NotePad.util;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.WeakHashMap;

public final class Literal {

    public static final boolean BOOLEAN_TRUE = true;
    public static final boolean BOOLEAN_FALSE = false;
    public final static String SOMETHING_WENT_WRONG = "Something went wrong.";
    public static final List<Map<String, Object>> EMPTY_ARRAYLIST = new ArrayList<Map<String, Object>>(0);
    public static final String ASC = "ASC";
    public static final Map<String, Object> EMPTY_HASHMAP = new WeakHashMap<String, Object>(0);
    public final static int ZERO_VALUE = 0;
    public final static String APPLICATION_JSON = "Accept=application/json";
    public final static int SIX = 6;
    public static final int FOUR_INT = 4;
    public static final String STATUS = "STATUS";
    public static final String ERROR = "ERROR";
    public final static String MESSAGE = "MESSAGE";
    public static final String API_GATE_WAY_NULL = "Kindly provide api gate way.";
    public final static String APPLICATION = "NOTEPAD";
    public final static String SUCCESS = "SUCCESS";
    public static final String API_GATE_WAY = "API_GATE_WAY";
    public static final String WRONG_GATEWAY = "Wrong api_gate_way.";
    public static final String REQUEST_DATA = "REQUEST_DATA";
    public static final String api_gateway = "api_gateway";
    public static final String EMPTY_STRING = "";
    public static final String name="name";
    public static final String PROJECT_NAME_NULL = "Kindly provide project name";
    public static final String description = "description";
    public static final int DESCRIPTION_LENGTH = 10000;
    public static final String DESCRIPTION_EXCEED = "Description length exceeded";
    public static final String API_TIME = "API_TIME";
    public static final String DOCBOOK_PROJECT_UPDATED = "Project details updated in docbook";
    public static final String icon = "icon";
    public static final String _id="_id";
    public static final String id ="id";
    public static final String PROJECT_ID_NULL = "Kindly provide project id";
    public static final String update_time_ms = "update_time_ms";
    public static final String update_time = "update_time";
    public static final String DATA = "DATA";
    public static final String ALL = "ALL";
    public static final String sections = "sections";
    public static final String collapsed = "collapsed";
    public static final String project_id = "project_id";
    public static final String section_id = "section_id";
    public static final String SECTION_ID_NULL = "Kindly provide section id";
    public static final String SECTION_NAME_NULL = "Kindly provide a name for this section";
    public static final String SECTION_NAME_EXCEED = "The length of section name is too long";
    public static final String sequence = "sequence";
    public static final String content = "content";
    public static final String DOCBOOK_SECTION_UPDATED = "Section details updated in docbook";
    public static final int ONE_INT = 1;
    public static final String BOTH_ID_NULL = "Kindly provide project id or section id to delete";
    public static final String DELETED_SECTION = "Section deleted successfully";
    public static final String DELETED_PROJECT = "Project deleted successfully";
    public static final String editMode = "editMode";
}
